server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./asiagolf_dev;MODE=MYSQL
    username: asiaGolf
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always